### PR TITLE
add support for fish parser

### PR DESCRIPTION
**Pull request by Ilhan-Personal**
https://github.com/quentinlintz/cmdtop/issues/6
@quentinlintz could you please review?

### CODE REVIEW

**Comment by quentinlintz** [comment]
Sorry for the late review! Could you check off fish parser in the README Roadmap please?

**Comment by Ilhan-Personal** [comment]
No problems at all :) 
Added changes in the README. Thank you !

**Comment by quentinlintz** [comment]
I received this comment on Reddit about a fish parser, curious what you think about this:
> just a note: statistics like these won't work (well) with the default fish, because unlike bash history, fish will just overwrite the timestamp when you use the same command again. Eg. in .bash_history you might have 50 lines with cd or ls (without arguments), so you can count them. But in fish when you've done ls 50 times, you only have 1 line with the most recent timestamp. (Of course ls dirX and ls dirY are recorded separately, but it still skews the statistics). 

Probably no way around it and we'll have to deal with the way fish records command history?

**Comment by Ilhan-Personal** [comment]
Hmm I wasn't aware of this limitation, I remember testing this out on my machine
I'll check again and get back to you.

**Comment by quentinlintz** [comment]
We could merge anyway since it's probably a limitation we'll have to deal with if we want to support fish.

**Comment by Ilhan-Personal** [comment]
Heyy @quentinlintz I'm so sorry Its been a busy week for me at work, I didn't get time to check on this could you give me this week to investigate and push out a PR? ( if this is something we can tackle now )

**Comment by Ilhan-Personal** [comment]
lets merge this as you earlier suggested and I'll create a separate issue to track this limitation....would that be okay @quentinlintz ?

**Review by quentinlintz — APPROVED** [review]
Looks great -- thanks for adding support for fish!!

**Pull request merged**
